version: '3.8'

services:
  backend:
    build:
      context: ./Cnh_rapida
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=72.62.15.46,1433;Database=CNH_Rapido;User Id=sa;Password=bonhoj-kaCxyp-jyqty3;TrustServerCertificate=True
    ports:
      - "5038:8080" # Exposed for direct access if needed
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend
    restart: always
